### PR TITLE
setup ember-try w/ travis.ci

### PR DESCRIPTION
**Pull request by eriktrom**

### CODE REVIEW

**Comment by eriktrom** [comment]
this should work, but we'll find out :)

**Comment by runspired** [comment]
As the owner I have to set up travis, don't I?

**Comment by eriktrom** [comment]
yep - this should help though

**Comment by runspired** [comment]
Should be all setup.

**Comment by runspired** [comment]
Building: https://travis-ci.org/runspired/ember-gestures/builds

**Comment by eriktrom** [comment]
yeah build failed, i think this config may help.

https://github.com/ember-cli/ember-cli/blob/master/.travis.yml

will try in a bit

**Comment by eriktrom** [comment]
fyi - those tests fail on phantom 1.9.x on mac as well - phantom2 can't be built on the newest mac but can be built on linux, but can't say if that'll fix the issue (cause can't try phantom2 here)

your other repo has phantom2 config within .travis.yml - will copy that over this evening

**Pull request merged**
