### PR TITLE
Make `ember-getowner-polyfill` a dependency.

### PR DESCRIPTION
**Pull request by jhr007**

### CODE REVIEW

**Comment by olivierlesnicki** [comment]
Good job!

**Comment by olivierlesnicki** [comment]
Can we get a release?

**Comment by mike-north** [comment]
This fix doesn't fix :) To convince yourself of this, use the latest version of ember-cli and run...

```sh
ember new gesture-test && \
  cd gesture-test && \
  ember install ember-gestures && \
  ember g route a && \
  ember g acceptance-test a && \
  ember test ci
```
Tests will fail.

**Comment by runspired** [comment]
@mike-north you have to return `npm install` within `node_modules/ember-gestures` after making that change, this fix does work.

The problem I've bumped into though is that installing a dependency this way trumps an app's own definition of the dependency, and the definition by any addons that come before it in evaluation.  It's a perilous situation atm, and core is aware of it.

**Comment by runspired** [comment]
And to clarify, the reason you have to run `npm install` is because `dependencies` are auto installed by `npm`, `devDependencies` are not.

**Comment by mike-north** [comment]
@runspired this is still unconventional imo. Particularly if this is a nested addon dependency, you can run into some serious problems w/ this approach (and run into no problems with `addAddonToProject` - #46) (i.e., gesture lookup fails, the installation blueprint doesn't run at all, etc...).

**Comment by runspired** [comment]
@mike-north this is the approach recommended to me by members of ember-cli and ember core. The problem is, `addAddonToProject` suffers similar problems, and I've had no end up debugging addons that try to manage this via that method instead of dependencies.  There simply is not a good story here yet, and which approach is truly better in the face of that is hard to know.

**Comment by mike-north** [comment]
I'm aware that there are lots of philosophical discussion over dependency resolution w/ addons (having had much debate w/ Stef on this topic over many months ;). I'll have to fork this in the mean time since `addAddonToProject` is the only approach that currently offers a decent, practical story in the nested addon case (I was looking into using this for [ember-cli-materialize](https://github.com/mike-north/ember-cli-materialize)).

**Comment by runspired** [comment]
@mike-north will publish with your method :) I'm documenting why `dependencies` works and the reasons for this path, not rejecting your proposal.  Most my addons have followed the `addAddonToProject` path, and I've recently been bitten hard by an addon using `dependencies`.  I've been bitten similarly hard by `addAddonToProject`, but in a much more debuggable way.

**Pull request merged**
