### PR TITLE
fix event listener & memory leak

### PR DESCRIPTION
**Pull request by Leooo**

### CODE REVIEW

**Comment by Leooo** [comment]
@runspired can we have a new release? The fix in this PR is a very big issue when running tests (memory leak)

**Comment by runspired** [comment]
Ping @eriktrom do I need to give you expanded permissions for these sorts of things and release?

**Comment by eriktrom** [comment]
Just npm publish rights.

**Comment by runspired** [comment]
@eriktrom you should now have these rights.

**Comment by eriktrom** [comment]
word @runspired

**Comment by Leooo** [comment]
@eriktrom ping?

**Comment by eriktrom** [comment]
@Leooo - thanks for the ping - will release within hour. Sorry for delay.

**Comment by eriktrom** [comment]
@Leooo - released - sorry for delay but thanks for finding and fixing this issue - appreciated

**Comment by Leooo** [comment]
Thanks @eriktrom. Shall we also create a 0.4.3 release?

**Comment by eriktrom** [comment]
Yep - published that yesterday. 😉

**Comment by Leooo** [comment]
@eriktrom no, the tag is missing

**Comment by Leooo** [comment]
releases => new => 0.4.3, then npm publish (or you will not create a new release on npm actually)

**Comment by eriktrom** [comment]
@Leooo - thanks for the feedback - but I've never had issues publishing via

`npm version patch && git push origin master && npm publish`

You do have to push the version bump in package.json to the base branch on github, but AFAIK a tag is not required.

also, i just installed a new ember app and ran `ember install ember-gestures` and package.json accurately reflected the new version. 

If however something has changed with npm publishing in the past few months that recommends this, i'd love a link if u have one.

Thanks again

**Comment by Leooo** [comment]
ALright you taught me something then: that npm version can differ from github versions. I've always been used to take the version from github release tags before but that must work indeed if people know there is a version after 4.2 (looking at the github releases they wouldnt)

**Comment by runspired** [comment]
@eriktrom if you could, when you push a release always ensure to create a tag as well :)

**Comment by eriktrom** [comment]
@runspired - sure thing
@Leooo - thanks for raising this, making a tag is best practice, good call

**Pull request merged**
